insert into RUNNER_ENTITY(AVERAGE_PACE,RUNNER_NAME) values(20,'SAnyi');
insert into RUNNER_ENTITY(AVERAGE_PACE,RUNNER_NAME) values(40,'V');
insert into RUNNER_ENTITY(AVERAGE_PACE,RUNNER_NAME) values(50,'C');
insert into RUNNER_ENTITY(AVERAGE_PACE,RUNNER_NAME) values(60,'D');